version: '2'

services:
  web:
    build: docker/web
    volumes:
      - ./:/var/www
    ports:
      - "8888:80"
    networks:
      - question

  app:
    build: docker/app
    volumes:
      - ./:/var/www
    networks:
      - question

  redis:
    image: redis
    networks:
      - question

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: question
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    ports:
      - "33061:3306"
    networks:
      - question

networks:
  question:
    driver: "bridge"
